import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className}  antialiased`}>
        <div className="min-h-screen max-w-[640px] md:max-w-[768px] lg:max-w-[1280px] xl:max-w-[1366px] mx-auto px-5">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
