import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import AuthContextProvider from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import ChatContextProvider from "@/context/ChatContext";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Next Js React Estate App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.className}>
      <AuthContextProvider>
        <ChatContextProvider>
          <body>
            <ToastContainer />
            <div className="min-h-screen max-w-[640px] md:max-w-[768px] lg:max-w-[1280px] xl:max-w-[1366px] mx-auto px-5">
              <Navbar />

              <div className="flex-1">
                {children}
              </div>
            </div>

            <div>
              <Footer />
            </div>
          </body>
        </ChatContextProvider>
      </AuthContextProvider>
    </html>
  );
}
